# Generated by Django 3.2.9 on 2022-03-21 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=6),
        ),
        migrations.AlterField(
            model_name='employeedetail',
            name='education',
            field=models.CharField(choices=[('Btech', 'BTech'), ('Mtech', 'Mtech'), ('BCA', 'BCA'), ('MCA', 'MCA')], max_length=6),
        ),
    ]
