# Generated by Django 3.2.9 on 2022-03-21 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_auto_20220321_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetail',
            name='salary',
            field=models.IntegerField(),
        ),
    ]
